name: build
on: pull_request

jobs:
    test:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install Dependencies
              run: npm i -ci

            - name: Compile
              run: npm run compile
            
            - name: Run Main
              run: node ./dist/app.js

