name: pre-build
on: push

jobs:
    job1:
        name: Setup Node.Js
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18
            
            - name: npm i
              run: npm i
    job2:
      name: Check Dependencies
      runs-on: ubuntu-latest
      needs: job1
      steps:
          - name: Checkout
            uses: actions/checkout@v3   
          - name: install
            run: |
              echo "***Job-2:"
              ls -lah
    