name: pre-build
on: push

jobs:
    job1:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: check Result
              run: ls -lah
    job2:
      name: Install Dependencies
      runs-on: ubuntu-latest
      needs: job1
      steps:
          - name: Checkout
            uses: actions/checkout@v3   
          - name: install
            run: |
              echo "***Job-2:"
              ls -lah
              npm i -ci

